name: Sincronizar com Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push para Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://fabiobaruch:$HF_TOKEN@huggingface.co/spaces/fabiobaruch/brachat-core main
